name: Update Spotify Now Playing
on:
  schedule:
    - cron: "*/10 * * * *"      # every 10 min
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: kittinan/spotify-github-profile@master
        with:
          username: v5nv4l5yu733wzvej1rxn4gcb          # spotify UID
          
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          output_image: spotify.svg
